# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSeleniumTest01():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_seleniumTest01(self):
    self.driver.get("http://the-internet.herokuapp.com//")
    self.driver.set_window_size(1092, 819)
    self.driver.find_element(By.LINK_TEXT, "Drag and Drop").click()
    dragged = self.driver.find_element(By.ID, "column-a")
    dropped = self.driver.find_element(By.ID, "column-b")
    actions = ActionChains(self.driver)
    actions.drag_and_drop(dragged, dropped).perform()
  
